# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12cb622016dc7f52b4385f4dc7fa564e6a7f59a55120c910c8ee74cef18543666e422118372e2bd2c782e679c401ccab81b9fa54d1cb95daeef36077706a13a8

test:
  secret_key_base: cc3cfaeda77638b60be9cf6f00fa29b79855958af41ba9d2c21d6014c45284835c1685ab58f2b7af4a777f30f3f0ce572052d5ee7f5ed6ec55a7f30c23e9f00b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
